/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddBus {
        "busname": string;
        "busnumber": string;
    }
    interface AdminNavbar {
    }
    interface BookedList {
    }
    interface BusSchedule {
        "city": string;
        "state": string;
    }
    interface BusScheduleShow {
    }
    interface BusShow {
    }
    interface LibeRouter {
    }
    interface LocationList {
        "city": string;
        "state": string;
        "terminal": string;
    }
    interface LocationListShow {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAddBusElement extends Components.AddBus, HTMLStencilElement {
    }
    var HTMLAddBusElement: {
        prototype: HTMLAddBusElement;
        new (): HTMLAddBusElement;
    };
    interface HTMLAdminNavbarElement extends Components.AdminNavbar, HTMLStencilElement {
    }
    var HTMLAdminNavbarElement: {
        prototype: HTMLAdminNavbarElement;
        new (): HTMLAdminNavbarElement;
    };
    interface HTMLBookedListElement extends Components.BookedList, HTMLStencilElement {
    }
    var HTMLBookedListElement: {
        prototype: HTMLBookedListElement;
        new (): HTMLBookedListElement;
    };
    interface HTMLBusScheduleElement extends Components.BusSchedule, HTMLStencilElement {
    }
    var HTMLBusScheduleElement: {
        prototype: HTMLBusScheduleElement;
        new (): HTMLBusScheduleElement;
    };
    interface HTMLBusScheduleShowElement extends Components.BusScheduleShow, HTMLStencilElement {
    }
    var HTMLBusScheduleShowElement: {
        prototype: HTMLBusScheduleShowElement;
        new (): HTMLBusScheduleShowElement;
    };
    interface HTMLBusShowElement extends Components.BusShow, HTMLStencilElement {
    }
    var HTMLBusShowElement: {
        prototype: HTMLBusShowElement;
        new (): HTMLBusShowElement;
    };
    interface HTMLLibeRouterElement extends Components.LibeRouter, HTMLStencilElement {
    }
    var HTMLLibeRouterElement: {
        prototype: HTMLLibeRouterElement;
        new (): HTMLLibeRouterElement;
    };
    interface HTMLLocationListElement extends Components.LocationList, HTMLStencilElement {
    }
    var HTMLLocationListElement: {
        prototype: HTMLLocationListElement;
        new (): HTMLLocationListElement;
    };
    interface HTMLLocationListShowElement extends Components.LocationListShow, HTMLStencilElement {
    }
    var HTMLLocationListShowElement: {
        prototype: HTMLLocationListShowElement;
        new (): HTMLLocationListShowElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "add-bus": HTMLAddBusElement;
        "admin-navbar": HTMLAdminNavbarElement;
        "booked-list": HTMLBookedListElement;
        "bus-schedule": HTMLBusScheduleElement;
        "bus-schedule-show": HTMLBusScheduleShowElement;
        "bus-show": HTMLBusShowElement;
        "libe-router": HTMLLibeRouterElement;
        "location-list": HTMLLocationListElement;
        "location-list-show": HTMLLocationListShowElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AddBus {
        "busname"?: string;
        "busnumber"?: string;
    }
    interface AdminNavbar {
    }
    interface BookedList {
    }
    interface BusSchedule {
        "city"?: string;
        "state"?: string;
    }
    interface BusScheduleShow {
    }
    interface BusShow {
    }
    interface LibeRouter {
    }
    interface LocationList {
        "city"?: string;
        "state"?: string;
        "terminal"?: string;
    }
    interface LocationListShow {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "add-bus": AddBus;
        "admin-navbar": AdminNavbar;
        "booked-list": BookedList;
        "bus-schedule": BusSchedule;
        "bus-schedule-show": BusScheduleShow;
        "bus-show": BusShow;
        "libe-router": LibeRouter;
        "location-list": LocationList;
        "location-list-show": LocationListShow;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-bus": LocalJSX.AddBus & JSXBase.HTMLAttributes<HTMLAddBusElement>;
            "admin-navbar": LocalJSX.AdminNavbar & JSXBase.HTMLAttributes<HTMLAdminNavbarElement>;
            "booked-list": LocalJSX.BookedList & JSXBase.HTMLAttributes<HTMLBookedListElement>;
            "bus-schedule": LocalJSX.BusSchedule & JSXBase.HTMLAttributes<HTMLBusScheduleElement>;
            "bus-schedule-show": LocalJSX.BusScheduleShow & JSXBase.HTMLAttributes<HTMLBusScheduleShowElement>;
            "bus-show": LocalJSX.BusShow & JSXBase.HTMLAttributes<HTMLBusShowElement>;
            "libe-router": LocalJSX.LibeRouter & JSXBase.HTMLAttributes<HTMLLibeRouterElement>;
            "location-list": LocalJSX.LocationList & JSXBase.HTMLAttributes<HTMLLocationListElement>;
            "location-list-show": LocalJSX.LocationListShow & JSXBase.HTMLAttributes<HTMLLocationListShowElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
